In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
words_df = pd.read_csv('~/Desktop/Project2/word_data.csv')

In [3]:
words_df['growth'] = words_df['30'] - words_df['16']

In [4]:
words_filtered = words_df[words_df['growth'] > 0]

In [5]:
words_desc = words_filtered.sort(['growth', '30'], ascending=[0, 0])

/Users/niccdias/anaconda/envs/py3k/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [6]:
words_desc = words_desc.reset_index()

In [7]:
words_desc['category'].unique()

array(['body_parts', 'action_words', 'clothing', 'descriptive_words',
       'outside', 'toys', 'furniture_rooms', 'games_routines', 'animals',
       'places', 'food_drink', 'household', 'vehicles', 'people',
       'pronouns', 'locations', 'helping_verbs', 'time_words',
       'quantifiers', 'question_words', 'connecting_words', 'sounds', nan], dtype=object)

In [12]:
words_desc[words_desc['category'] == 'animals'].tail(10)

,index,definition,type,category,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,growth
546,53,wolf,word,animals,0.02,0.01,0.08,0.06,0.09,0.11,0.12,0.23,0.28,0.32,0.39,0.39,0.57,0.43,0.58,0.56
555,44,pony,word,animals,0.03,0.02,0.06,0.12,0.14,0.22,0.28,0.24,0.31,0.34,0.44,0.46,0.59,0.51,0.58,0.55
566,21,cat,word,animals,0.42,0.45,0.53,0.66,0.68,0.68,0.80,0.85,0.84,0.86,0.94,0.88,0.96,0.96,0.95,0.53
588,17,bird,word,animals,0.48,0.47,0.63,0.66,0.76,0.70,0.80,0.84,0.88,0.91,0.95,0.94,0.97,0.93,0.97,0.49
589,27,duck,word,animals,0.48,0.52,0.61,0.67,0.72,0.67,0.81,0.85,0.88,0.88,0.95,0.93,0.98,0.91,0.97,0.49
590,26,donkey,word,animals,0.03,0.04,0.07,0.12,0.13,0.20,0.25,0.28,0.32,0.32,0.36,0.42,0.58,0.43,0.52,0.49
594,35,kitty,word,animals,0.45,0.38,0.60,0.64,0.61,0.69,0.76,0.79,0.79,0.84,0.88,0.84,0.94,0.89,0.94,0.49
609,33,hen,word,animals,0.01,0.01,0.03,0.06,0.08,0.13,0.16,0.19,0.22,0.25,0.30,0.26,0.48,0.33,0.46,0.45
618,39,moose,word,animals,0.03,0.05,0.07,0.11,0.09,0.11,0.21,0.23,0.28,0.28,0.35,0.36,0.52,0.42,0.48,0.45
684,25,dog,word,animals,0.68,0.72,0.78,0.83,0.82,0.85,0.87,0.94,0.92,0.94,0.98,0.96,0.99,0.97,0.96,0.28

In [8]:
avg_growth_by_category = []

for category in words_desc['category'].unique():
    cat_dict = {}
    df = words_desc[words_desc['category'] == category]
    avg_growth = np.mean(df['growth'])
    cat_dict['category'] = category
    cat_dict['avg_growth'] = avg_growth
    avg_growth_by_category.append(cat_dict)
    
avg_growth_df = pd.DataFrame(avg_growth_by_category)

In [9]:
avg_growth_clean = avg_growth_df.sort(['avg_growth'], ascending=[0]).reset_index()
del avg_growth_clean['index']

/Users/niccdias/anaconda/envs/py3k/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [11]:
avg_growth_clean.head(10)

   avg_growth           category
0    0.752621       action_words
1    0.737778         body_parts
2    0.733000          household
3    0.729032            outside
4    0.728235         food_drink
5    0.725000           vehicles
6    0.721270  descriptive_words
7    0.710606    furniture_rooms
8    0.694444               toys
9    0.679302            animals

In [12]:
categories = list(avg_growth_clean['category'][0:10]) + list(avg_growth_clean['category'][-10:])
categories = list(reversed(categories))
y_pos = np.arange(len(categories))
growths = list(avg_growth_clean['avg_growth'][0:10]) + list(avg_growth_clean['avg_growth'][-10:])
growths = list(reversed(growths))

plt.clf()
plt.barh(y_pos, growths)
plt.yticks(y_pos, categories)
plt.ylabel('Type of word')
plt.xlabel('Average growth')
plt.title('Some words are more useful than others')

plt.savefig("growth_by_type.pdf", transparent=True, bbox_inches='tight')

In [314]:
animals = words_desc[words_desc['category'] == 'animals']
animals = animals.reset_index()
del animals['index']

In [317]:
animals.tail(10)

,definition,type,category,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,growth
33,wolf,word,animals,0.02,0.01,0.08,0.06,0.09,0.11,0.12,0.23,0.28,0.32,0.39,0.39,0.57,0.43,0.58,0.56
34,pony,word,animals,0.03,0.02,0.06,0.12,0.14,0.22,0.28,0.24,0.31,0.34,0.44,0.46,0.59,0.51,0.58,0.55
35,cat,word,animals,0.42,0.45,0.53,0.66,0.68,0.68,0.80,0.85,0.84,0.86,0.94,0.88,0.96,0.96,0.95,0.53
36,bird,word,animals,0.48,0.47,0.63,0.66,0.76,0.70,0.80,0.84,0.88,0.91,0.95,0.94,0.97,0.93,0.97,0.49
37,duck,word,animals,0.48,0.52,0.61,0.67,0.72,0.67,0.81,0.85,0.88,0.88,0.95,0.93,0.98,0.91,0.97,0.49
38,donkey,word,animals,0.03,0.04,0.07,0.12,0.13,0.20,0.25,0.28,0.32,0.32,0.36,0.42,0.58,0.43,0.52,0.49
39,kitty,word,animals,0.45,0.38,0.60,0.64,0.61,0.69,0.76,0.79,0.79,0.84,0.88,0.84,0.94,0.89,0.94,0.49
40,hen,word,animals,0.01,0.01,0.03,0.06,0.08,0.13,0.16,0.19,0.22,0.25,0.30,0.26,0.48,0.33,0.46,0.45
41,moose,word,animals,0.03,0.05,0.07,0.11,0.09,0.11,0.21,0.23,0.28,0.28,0.35,0.36,0.52,0.42,0.48,0.45
42,dog,word,animals,0.68,0.72,0.78,0.83,0.82,0.85,0.87,0.94,0.92,0.94,0.98,0.96,0.99,0.97,0.96,0.28

In [192]:
x = [16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
elephant = animals.iloc[0, 3:18]
butterfly = animals.iloc[1, 3:18]
kitty = animals.iloc[-4, 3:18]
hen = animals.iloc[-3, 3:18]
moose = animals.iloc[-2, 3:18]
dog = animals.iloc[-1, 3:18]

In [300]:
plt.clf()
plt.plot(x, elephant, label = "elephant")
plt.plot(x, butterfly, label = "butterfly")
plt.plot(x, kitty, label = "kitty")
plt.plot(x, hen, label = "hen")
plt.plot(x, moose, label = "moose")
plt.plot(x, dog, label = "dog")
plt.xlabel("Age in months")
plt.ylabel("Percentage of kids that know the word")
plt.title("What animals do kids learn?")
plt.legend(bbox_to_anchor=(0., 1.02, 1., .102), loc=3,
           ncol=2, mode="expand", borderaxespad=0.)

plt.savefig("animals_growth.pdf", transparent=True, bbox_inches='tight')

/Users/niccdias/anaconda/envs/py3k/lib/python3.5/site-packages/matplotlib/figure.py:1742: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "

In [274]:
food_drink = words_desc[words_desc['category'] == 'food_drink']
food_drink = food_drink.reset_index()
del food_drink['index'], food_drink['level_0']

In [275]:
food_drink

,definition,type,category,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,growth
0,orange (food),word,food_drink,0.07,0.11,0.22,0.32,0.34,0.41,0.53,0.61,0.62,0.66,0.79,0.78,0.90,0.87,0.94,0.87
1,candy,word,food_drink,0.07,0.12,0.23,0.33,0.35,0.41,0.50,0.59,0.66,0.75,0.81,0.79,0.92,0.87,0.93,0.86
2,pizza,word,food_drink,0.10,0.14,0.31,0.37,0.46,0.48,0.62,0.71,0.74,0.79,0.85,0.89,0.94,0.88,0.96,0.86
3,grapes,word,food_drink,0.09,0.15,0.29,0.37,0.41,0.45,0.59,0.63,0.69,0.73,0.79,0.83,0.90,0.86,0.95,0.86
4,popcorn,word,food_drink,0.04,0.08,0.18,0.22,0.28,0.33,0.38,0.44,0.58,0.63,0.71,0.69,0.84,0.76,0.90,0.86
5,sandwich,word,food_drink,0.02,0.03,0.10,0.18,0.19,0.23,0.37,0.44,0.50,0.56,0.61,0.72,0.85,0.79,0.88,0.86
6,cake,word,food_drink,0.08,0.10,0.25,0.32,0.36,0.40,0.58,0.64,0.76,0.77,0.81,0.84,0.92,0.89,0.93,0.85
7,carrots,word,food_drink,0.06,0.07,0.20,0.23,0.26,0.35,0.42,0.47,0.57,0.60,0.69,0.69,0.86,0.80,0.91,0.85
8,ice cream,word,food_drink,0.10,0.14,0.26,0.36,0.39,0.37,0.60,0.65,0.71,0.78,0.87,0.85,0.93,0.90,0.95,0.85
9,french fries,word,food_drink,0.07,0.11,0.22,0.33,0.33,0.39,0.49,0.56,0.62,0.70,0.80,0.78,0.90,0.81,0.91,0.84
10,chocolate,word,food_drink,0.03,0.04,0.11,0.14,0.21,0.23,0.38,0.41,0.50,0.51,0.59,0.68,0.79,0.74,0.87,0.84
11,chicken (food),word,food_drink,0.08,0.09,0.24,0.30,0.36,0.45,0.54,0.56,0.64,0.72,0.75,0.82,0.90,0.84,0.91,0.83
12,cereal,word,food_drink,0.11,0.14,0.30,0.37,0.38,0.49,0.51,0.63,0.68,0.74,0.81,0.77,0.92,0.86,0.94,0.83
13,corn,word,food_drink,0.05,0.08,0.17,0.24,0.27,0.30,0.44,0.48,0.55,0.60,0.72,0.73,0.84,0.75,0.88,0.83
14,pancake,word,food_drink,0.05,0.07,0.17,0.23,0.23,0.26,0.41,0.50,0.55,0.58,0.65,0.72,0.80,0.73,0.88,0.83
15,raisin,word,food_drink,0.05,0.07,0.19,0.26,0.27,0.31,0.46,0.47,0.56,0.61,0.69,0.71,0.81,0.76,0.88,0.83
16,spaghetti,word,food_drink,0.05,0.08,0.15,0.18,0.23,0.28,0.34,0.46,0.55,0.57,0.69,0.68,0.83,0.75,0.88,0.83
17,peanut butter,word,food_drink,0.03,0.06,0.12,0.22,0.19,0.28,0.41,0.44,0.50,0.58,0.61,0.71,0.82,0.75,0.86,0.83
18,potato chip,word,food_drink,0.04,0.08,0.18,0.23,0.24,0.32,0.35,0.46,0.51,0.61,0.69,0.64,0.84,0.73,0.86,0.82
19,food,word,food_drink,0.07,0.14,0.21,0.29,0.31,0.37,0.48,0.55,0.58,0.61,0.69,0.70,0.83,0.83,0.88,0.81
20,butter,word,food_drink,0.04,0.05,0.12,0.19,0.24,0.30,0.42,0.44,0.52,0.60,0.68,0.71,0.82,0.73,0.85,0.81
21,hamburger,word,food_drink,0.02,0.05,0.11,0.17,0.20,0.28,0.36,0.44,0.47,0.60,0.70,0.72,0.78,0.77,0.83,0.81
22,egg,word,food_drink,0.12,0.16,0.26,0.35,0.41,0.49,0.57,0.64,0.68,0.74,0.79,0.79,0.91,0.83,0.92,0.80
23,strawberry,word,food_drink,0.06,0.09,0.17,0.21,0.26,0.35,0.43,0.51,0.54,0.61,0.68,0.65,0.80,0.80,0.86,0.80
24,yogurt,word,food_drink,0.08,0.15,0.28,0.33,0.34,0.38,0.53,0.54,0.57,0.61,0.62,0.71,0.75,0.74,0.87,0.79
25,bread,word,food_drink,0.15,0.14,0.30,0.38,0.41,0.49,0.59,0.64,0.70,0.78,0.79,0.84,0.93,0.90,0.94,0.79
26,applesauce,word,food_drink,0.05,0.05,0.14,0.15,0.23,0.28,0.39,0.45,0.48,0.50,0.54,0.57,0.73,0.65,0.84,0.79
27,noodles,word,food_drink,0.09,0.09,0.21,0.26,0.32,0.38,0.46,0.48,0.56,0.56,0.66,0.65,0.80,0.69,0.87,0.78
28,ice,word,food_drink,0.11,0.12,0.25,0.34,0.36,0.41,0.51,0.59,0.64,0.72,0.71,0.75,0.86,0.81,0.88,0.77
29,pumpkin,word,food_drink,0.04,0.05,0.14,0.18,0.20,0.25,0.32,0.39,0.48,0.47,0.56,0.57,0.74,0.65,0.81,0.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,coffee,word,food_drink,0.04,0.04,0.15,0.20,0.24,0.28,0.40,0.43,0.50,0.58,0.61,0.63,0.79,0.67,0.78,0.74
39,pretzel,word,food_drink,0.04,0.05,0.12,0.17,0.19,0.19,0.33,0.34,0.43,0.44,0.46,0.50,0.75,0.59,0.78,0.74
40,muffin,word,food_drink,0.02,0.04,0.09,0.14,0.21,0.20,0.35,0.33,0.43,0.42,0.51,0.56,0.69,0.67,0.75,0.73
41,pickle,word,food_drink,0.02,0.05,0.13,0.17,0.17,0.19,0.29,0.40,0.40,0.49,0.55,0.54,0.69,0.64,0.74,0.72
42,meat,word,food_drink,0.04,0.06,0.11,0.17,0.23,0.24,0.29,0.36,0.45,0.48,0.61,0.55,0.70,0.60,0.74,0.70
43,nuts,word,food_drink,0.01,0.03,0.05,0.11,0.12,0.17,0.17,0.26,0.35,0.34,0.51,0.47,0.61,0.62,0.71,0.70
44,peas,word,food_drink,0.12,0.09,0.21,0.29,0.28,0.31,0.37,0.47,0.53,0.54,0.65,0.61,0.73,0.65,0.81,0.69
45,donut,word,food_drink,0.03,0.05,0.10,0.12,0.15,0.18,0.26,0.36,0.37,0.46,0.53,0.54,0.68,0.62,0.72,0.69
46,cheerios,word,food_drink,0.16,0.19,0.27,0.29,0.34,0.40,0.47,0.52,0.52,0.61,0.63,0.69,0.79,0.74,0.84,0.68
47,gum,word,food_drink,0.01,0.04,0.08,0.15,0.13,0.16,0.31,0.30,0.34,0.44,0.56,0.54,0.61,0.63,0.69,0.68
48,green beans,word,food_drink,0.03,0.04,0.11,0.11,0.15,0.18,0.23,0.30,0.36,0.41,0.43,0.42,0.59,0.49,0.68,0.65
49,water (beverage),word,food_drink,0.30,0.32,0.48,0.58,0.63,0.62,0.75,0.80,0.84,0.86,0.89,0.95,0.95,0.92,0.95,0.65
50,vitamins,word,food_drink,0.02,0.05,0.06,0.12,0.14,0.15,0.22,0.28,0.33,0.41,0.49,0.51,0.61,0.59,0.66,0.64
51,lollipop,word,food_drink,0.01,0.03,0.08,0.12,0.13,0.16,0.24,0.24,0.32,0.44,0.39,0.49,0.62,0.60,0.65,0.64
52,apple,word,food_drink,0.33,0.43,0.58,0.62,0.68,0.72,0.85,0.88,0.87,0.89,0.92,0.95,0.98,0.95,0.97,0.64
53,milk,word,food_drink,0.34,0.43,0.57,0.72,0.67,0.72,0.79,0.88,0.86,0.87,0.93,0.93,0.97,0.96,0.97,0.63
54,sauce,word,food_drink,0.02,0.01,0.05,0.08,0.14,0.11,0.26,0.25,0.33,0.29,0.38,0.39,0.59,0.57,0.64,0.62
55,cracker,word,food_drink,0.34,0.32,0.50,0.58,0.59,0.59,0.71,0.78,0.77,0.81,0.84,0.84,0.95,0.86,0.96,0.62
56,cheese,word,food_drink,0.36,0.41,0.57,0.64,0.69,0.67,0.78,0.83,0.87,0.86,0.92,0.93,0.96,0.92,0.97,0.61
57,cookie,word,food_drink,0.38,0.36,0.57,0.69,0.66,0.70,0.78,0.84,0.88,0.91,0.94,0.91,0.98,0.94,0.98,0.60
58,jello,word,food_drink,0.02,0.04,0.08,0.10,0.12,0.14,0.18,0.19,0.30,0.36,0.43,0.45,0.60,0.47,0.62,0.60
59,pudding,word,food_drink,0.01,0.02,0.06,0.07,0.09,0.09,0.18,0.17,0.26,0.31,0.35,0.34,0.54,0.46,0.61,0.60
60,salt,word,food_drink,0.01,0.01,0.03,0.06,0.09,0.11,0.20,0.17,0.26,0.30,0.35,0.43,0.56,0.50,0.61,0.60
61,soda/pop,word,food_drink,0.05,0.07,0.13,0.17,0.22,0.28,0.31,0.36,0.39,0.45,0.53,0.51,0.72,0.59,0.64,0.59
62,melon,word,food_drink,0.03,0.02,0.08,0.11,0.16,0.21,0.22,0.30,0.31,0.35,0.46,0.46,0.56,0.46,0.62,0.59
63,juice,word,food_drink,0.44,0.31,0.58,0.67,0.69,0.76,0.82,0.85,0.86,0.86,0.95,0.90,0.97,0.91,0.98,0.54
64,coke,word,food_drink,0.04,0.04,0.09,0.13,0.15,0.18,0.25,0.20,0.34,0.40,0.41,0.37,0.54,0.44,0.56,0.52
65,vanilla,word,food_drink,0.00,0.00,0.02,0.03,0.05,0.05,0.08,0.09,0.12,0.19,0.19,0.30,0.35,0.35,0.45,0.45
66,banana,word,food_drink,0.52,0.56,0.66,0.73,0.76,0.77,0.87,0.90,0.87,0.91,0.92,0.93,0.98,0.94,0.97,0.45
67,tuna,word,food_drink,0.01,0.02,0.05,0.04,0.06,0.10,0.19,0.17,0.17,0.26,0.32,0.36,0.43,0.34,0.43,0.42

In [276]:
orange = food_drink.iloc[0, 3:18]
candy = food_drink.iloc[1, 3:18]
pizza = food_drink.iloc[2, 3:18]
vanilla = food_drink.iloc[-3, 3:18]
banana = food_drink.iloc[-2, 3:18]
tuna = food_drink.iloc[-1, 3:18]

In [298]:
plt.clf()
plt.plot(x, orange, label = 'orange')
plt.plot(x, candy, label = 'candy')
plt.plot(x, pizza, label = 'pizza')
plt.plot(x, vanilla, label = 'vanilla')
plt.plot(x, banana, label = 'banana')
plt.plot(x, tuna, label = 'tuna')
plt.xlabel('Age in months')
plt.ylabel('Percentage of kids that know the word')
plt.title('Which foods to kids learn?')
plt.legend(bbox_to_anchor=(0., 1.02, 1., .102), loc=3,
           ncol=2, mode="expand", borderaxespad=0.)

plt.savefig("food_growth.pdf", transparent=True, bbox_inches='tight')

/Users/niccdias/anaconda/envs/py3k/lib/python3.5/site-packages/matplotlib/figure.py:1742: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "

In [201]:
child_df = pd.read_csv('~/Desktop/Project2/child_data.csv')

In [280]:
child_df.head()

   data_id language form  age  gender        mom_ed  comprehension  production
0    49245  English   WG   17  Female      Graduate            150         109
1    49246  English   WG   17    Male      Graduate            185          18
2    49247  English   WG   17    Male  Some College            224         104
3    49248  English   WG   17    Male       College            209         125
4    49249  English   WG   18  Female  Some College            283         129

In [206]:
child_df['mom_ed'].unique()

array(['Graduate', 'Some College', 'College', 'Some Secondary',
       'Some Graduate', 'Secondary', nan, 'Primary'], dtype=object)

In [226]:
avg_comp_by_mom_ed = []

for ed in child_df['mom_ed'].unique():
    ed_dict = {}
    df = child_df[child_df['mom_ed'] == ed]
    avg_comp = np.mean(df['comprehension'])
    ed_dict['ed_level'] = ed
    ed_dict['avg_comp'] = avg_comp
    avg_comp_by_mom_ed.append(ed_dict)
    
mom_ed_comp_df = pd.DataFrame(avg_comp_by_mom_ed)

In [229]:
mom_comp_clean = mom_ed_comp_df.sort(['avg_comp'], ascending=0).reset_index()
del mom_comp_clean['index']
mom_comp_clean = mom_comp_clean.drop([7])

/Users/niccdias/anaconda/envs/py3k/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [230]:
mom_comp_clean

     avg_comp        ed_level
0  255.029167        Graduate
1  254.698492   Some Graduate
2  235.815628         College
3  227.461078       Secondary
4  216.662818    Some College
5  180.542105  Some Secondary
6  131.900000         Primary

In [301]:
y_pos = np.arange(len(mom_comp_clean['ed_level']))
 
plt.clf()    
plt.barh(y_pos, list(reversed(mom_comp_clean['avg_comp'])))
plt.yticks(y_pos, list(reversed(mom_comp_clean['ed_level'])))
plt.ylabel("Mother's level of education")
plt.xlabel("Average number of words understood")
plt.title("Kids with educated moms understand more words")

plt.savefig("mom_comp.pdf", transparent=True, bbox_inches='tight')

/Users/niccdias/anaconda/envs/py3k/lib/python3.5/site-packages/matplotlib/figure.py:1742: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "

In [244]:
avg_pro_by_mom_ed = []

for ed in child_df['mom_ed'].unique():
    ed_dict = {}
    df = child_df[child_df['mom_ed'] == ed]
    avg_pro = np.mean(df['production'])
    ed_dict['ed_level'] = ed
    ed_dict['avg_pro'] = avg_pro
    avg_pro_by_mom_ed.append(ed_dict)
    
mom_ed_pro_df = pd.DataFrame(avg_pro_by_mom_ed)

In [247]:
mom_pro_clean = mom_ed_pro_df.sort(['avg_pro'], ascending=0).reset_index()
del mom_pro_clean['index']
mom_pro_clean = mom_pro_clean.drop([7])

/Users/niccdias/anaconda/envs/py3k/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [251]:
mom_pro_clean

      avg_pro        ed_level
0  235.827778        Graduate
1  234.095477   Some Graduate
2  212.007902         College
3  189.661677       Secondary
4  187.922633    Some College
5  149.384211  Some Secondary
6  116.400000         Primary

In [302]:
y_pos = np.arange(len(mom_pro_clean['ed_level']))
 
plt.clf()    
plt.barh(y_pos, list(reversed(mom_pro_clean['avg_pro'])))
plt.yticks(y_pos, list(reversed(mom_pro_clean['ed_level'])))
plt.ylabel("Mother's level of education")
plt.xlabel("Average number of words used")
plt.title("Kids with educated moms use more words")

plt.savefig("mom_pro.pdf", transparent=True, bbox_inches='tight')

/Users/niccdias/anaconda/envs/py3k/lib/python3.5/site-packages/matplotlib/figure.py:1742: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "